### PR TITLE
Bugfixes: Sharepoint drive access and listing large folders + lint

### PR DESCRIPTION
**Pull request by odgalvin**
This PR fixes a mistake in my last PR to enable connecting to a Sharepoint site's drive. Also some random code cleanup.

### CODE REVIEW

**Comment by rkhwaja** [comment]
Can you drop the log interpolation stuff? I'd rather prioritize readability than such a minor performance improvement

**Comment by odgalvin** [comment]
Sure, that's done! I did that without thinking really after I ran pylint

**Comment by rkhwaja** [comment]
I see a couple of test failures when I run this branch on my local system. I think that test_download_as_format is broken on the OneDrive service. The other broken one is test_scandir but I'll fix it in a subsequent commit.

**Comment by odgalvin** [comment]
Thanks. Yeah that's fine, I'll try and keep things separate. It was just little bits I noticed while getting it to work for our use case.

I'll have a look at the test failures too on my end.

**Pull request merged**
